/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __mars_message_CleanComponents_hpp__
#define __mars_message_CleanComponents_hpp__

#include <lcm/lcm_coretypes.h>

#include "mars_message/Component.hpp"
#include "mars_message/Component.hpp"
#include "mars_message/Component.hpp"
#include "mars_message/Component.hpp"
#include "mars_message/Component.hpp"
#include "mars_message/Component.hpp"
#include "mars_message/Component.hpp"

namespace mars_message
{

class CleanComponents
{
    public:
        mars_message::Component sideBrush;

        mars_message::Component mainBrush;

        mars_message::Component roller;

        mars_message::Component waterTank;

        mars_message::Component mop;

        mars_message::Component waterPump;

        mars_message::Component fan;

#ifdef __NLOHMANN_JSON_CPP
    public:
        NLOHMANN_DEFINE_TYPE_INTRUSIVE(CleanComponents, sideBrush, mainBrush, roller, waterTank, mop, waterPump, fan)
#endif
    public:
        bool operator==(const CleanComponents& other) const
        {
            return sideBrush == other.sideBrush && mainBrush == other.mainBrush && roller == other.roller && waterTank == other.waterTank && mop == other.mop && waterPump == other.waterPump && fan == other.fan;
        }
    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "CleanComponents"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int CleanComponents::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int CleanComponents::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int CleanComponents::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t CleanComponents::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* CleanComponents::getTypeName()
{
    return "CleanComponents";
}

int CleanComponents::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = this->sideBrush._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->mainBrush._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->roller._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->waterTank._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->mop._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->waterPump._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->fan._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int CleanComponents::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = this->sideBrush._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->mainBrush._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->roller._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->waterTank._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->mop._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->waterPump._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->fan._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int CleanComponents::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->sideBrush._getEncodedSizeNoHash();
    enc_size += this->mainBrush._getEncodedSizeNoHash();
    enc_size += this->roller._getEncodedSizeNoHash();
    enc_size += this->waterTank._getEncodedSizeNoHash();
    enc_size += this->mop._getEncodedSizeNoHash();
    enc_size += this->waterPump._getEncodedSizeNoHash();
    enc_size += this->fan._getEncodedSizeNoHash();
    return enc_size;
}

uint64_t CleanComponents::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == CleanComponents::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, CleanComponents::getHash };

    uint64_t hash = 0x10857288fd016a69LL +
         mars_message::Component::_computeHash(&cp) +
         mars_message::Component::_computeHash(&cp) +
         mars_message::Component::_computeHash(&cp) +
         mars_message::Component::_computeHash(&cp) +
         mars_message::Component::_computeHash(&cp) +
         mars_message::Component::_computeHash(&cp) +
         mars_message::Component::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
