/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __mars_message_AlarmInfo_hpp__
#define __mars_message_AlarmInfo_hpp__

#include <lcm/lcm_coretypes.h>

#include <string>

namespace mars_message
{

class AlarmInfo
{
    public:
        std::string appName;

        std::string logType;

        std::string logValue;

#ifdef __NLOHMANN_JSON_CPP
    public:
        NLOHMANN_DEFINE_TYPE_INTRUSIVE(AlarmInfo, appName, logType, logValue)
#endif
#ifdef __MSGPACK
    public:
        MSGPACK_DEFINE(AlarmInfo, appName, logType, logValue)
#endif
    public:
        bool operator==(const AlarmInfo& other) const
        {
            return appName == other.appName && logType == other.logType && logValue == other.logValue;
        }
    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "AlarmInfo"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int AlarmInfo::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int AlarmInfo::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int AlarmInfo::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t AlarmInfo::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* AlarmInfo::getTypeName()
{
    return "AlarmInfo";
}

int AlarmInfo::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    char* appName_cstr = const_cast<char*>(this->appName.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &appName_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* logType_cstr = const_cast<char*>(this->logType.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &logType_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* logValue_cstr = const_cast<char*>(this->logValue.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &logValue_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int AlarmInfo::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    int32_t __appName_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__appName_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__appName_len__ > maxlen - pos) return -1;
    this->appName.assign(
        static_cast<const char*>(buf) + offset + pos, __appName_len__ - 1);
    pos += __appName_len__;

    int32_t __logType_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__logType_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__logType_len__ > maxlen - pos) return -1;
    this->logType.assign(
        static_cast<const char*>(buf) + offset + pos, __logType_len__ - 1);
    pos += __logType_len__;

    int32_t __logValue_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__logValue_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__logValue_len__ > maxlen - pos) return -1;
    this->logValue.assign(
        static_cast<const char*>(buf) + offset + pos, __logValue_len__ - 1);
    pos += __logValue_len__;

    return pos;
}

int AlarmInfo::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->appName.size() + 4 + 1;
    enc_size += this->logType.size() + 4 + 1;
    enc_size += this->logValue.size() + 4 + 1;
    return enc_size;
}

uint64_t AlarmInfo::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x6fae75a6b31e8806LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
