// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#ifndef _mars_message_Quaternion_h
#define _mars_message_Quaternion_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _mars_message_Quaternion mars_message_Quaternion;
struct _mars_message_Quaternion
{
    double     w;
    double     x;
    double     y;
    double     z;
};

/**
 * Create a deep copy of a mars_message_Quaternion.
 * When no longer needed, destroy it with mars_message_Quaternion_destroy()
 */
mars_message_Quaternion* mars_message_Quaternion_copy(const mars_message_Quaternion* to_copy);

/**
 * Destroy an instance of mars_message_Quaternion created by mars_message_Quaternion_copy()
 */
void mars_message_Quaternion_destroy(mars_message_Quaternion* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _mars_message_Quaternion_subscription_t mars_message_Quaternion_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * mars_message_Quaternion is received.
 */
typedef void(*mars_message_Quaternion_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const mars_message_Quaternion *msg, void *userdata);

/**
 * Publish a message of type mars_message_Quaternion using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int mars_message_Quaternion_publish(lcm_t *lcm, const char *channel, const mars_message_Quaternion *msg);

/**
 * Subscribe to messages of type mars_message_Quaternion using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
mars_message_Quaternion_subscription_t* mars_message_Quaternion_subscribe(
    lcm_t *lcm, const char *channel, mars_message_Quaternion_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by mars_message_Quaternion_subscribe()
 */
int mars_message_Quaternion_unsubscribe(lcm_t *lcm, mars_message_Quaternion_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int mars_message_Quaternion_subscription_set_queue_capacity(
    mars_message_Quaternion_subscription_t* subs, int num_messages);

/**
 * Encode a message of type mars_message_Quaternion into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to mars_message_Quaternion_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int mars_message_Quaternion_encode(void *buf, int offset, int maxlen, const mars_message_Quaternion *p);

/**
 * Decode a message of type mars_message_Quaternion from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with mars_message_Quaternion_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int mars_message_Quaternion_decode(const void *buf, int offset, int maxlen, mars_message_Quaternion *msg);

/**
 * Release resources allocated by mars_message_Quaternion_decode()
 * @return 0
 */
int mars_message_Quaternion_decode_cleanup(mars_message_Quaternion *p);

/**
 * Check how many bytes are required to encode a message of type mars_message_Quaternion
 */
int mars_message_Quaternion_encoded_size(const mars_message_Quaternion *p);

// LCM support functions. Users should not call these
int64_t __mars_message_Quaternion_get_hash(void);
uint64_t __mars_message_Quaternion_hash_recursive(const __lcm_hash_ptr *p);
int __mars_message_Quaternion_encode_array(
    void *buf, int offset, int maxlen, const mars_message_Quaternion *p, int elements);
int __mars_message_Quaternion_decode_array(
    const void *buf, int offset, int maxlen, mars_message_Quaternion *p, int elements);
int __mars_message_Quaternion_decode_array_cleanup(mars_message_Quaternion *p, int elements);
int __mars_message_Quaternion_encoded_array_size(const mars_message_Quaternion *p, int elements);
int __mars_message_Quaternion_clone_array(const mars_message_Quaternion *p, mars_message_Quaternion *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
