"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

import baofei_message.Rect2d

class CleanArea(object):
    __slots__ = ["area", "cleanNum"]

    __typenames__ = ["baofei_message.Rect2d", "int8_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.area = baofei_message.Rect2d()
        self.cleanNum = 0

    def encode(self):
        buf = BytesIO()
        buf.write(CleanArea._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.area._get_packed_fingerprint() == baofei_message.Rect2d._get_packed_fingerprint()
        self.area._encode_one(buf)
        buf.write(struct.pack(">b", self.cleanNum))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != CleanArea._get_packed_fingerprint():
            raise ValueError("Decode error")
        return CleanArea._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = CleanArea()
        self.area = baofei_message.Rect2d._decode_one(buf)
        self.cleanNum = struct.unpack(">b", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if CleanArea in parents: return 0
        newparents = parents + [CleanArea]
        tmphash = (0x6053bf00ab50d2af+ baofei_message.Rect2d._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if CleanArea._packed_fingerprint is None:
            CleanArea._packed_fingerprint = struct.pack(">Q", CleanArea._get_hash_recursive([]))
        return CleanArea._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", CleanArea._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.area.from_dict(j["area"])
        self.cleanNum = j["cleanNum"]

    def to_dict(self):
        j = {}
        j["area"] = self.area.to_dict()
        j["cleanNum"] = self.cleanNum
        return j

