"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

class Grid2d(object):
    __slots__ = ["x", "y"]

    __typenames__ = ["int32_t", "int32_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.x = 0
        self.y = 0

    def encode(self):
        buf = BytesIO()
        buf.write(Grid2d._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ii", self.x, self.y))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Grid2d._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Grid2d._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Grid2d()
        self.x, self.y = struct.unpack(">ii", buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if Grid2d in parents: return 0
        tmphash = (0xa7d5c704b1074f64) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Grid2d._packed_fingerprint is None:
            Grid2d._packed_fingerprint = struct.pack(">Q", Grid2d._get_hash_recursive([]))
        return Grid2d._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Grid2d._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.x = j["x"]
        self.y = j["y"]

    def to_dict(self):
        j = {}
        j["x"] = self.x
        j["y"] = self.y
        return j

