"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

import baofei_message.Grid2d

class Line2d(object):
    __slots__ = ["start", "end"]

    __typenames__ = ["baofei_message.Grid2d", "baofei_message.Grid2d"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.start = baofei_message.Grid2d()
        self.end = baofei_message.Grid2d()

    def encode(self):
        buf = BytesIO()
        buf.write(Line2d._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.start._get_packed_fingerprint() == baofei_message.Grid2d._get_packed_fingerprint()
        self.start._encode_one(buf)
        assert self.end._get_packed_fingerprint() == baofei_message.Grid2d._get_packed_fingerprint()
        self.end._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Line2d._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Line2d._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Line2d()
        self.start = baofei_message.Grid2d._decode_one(buf)
        self.end = baofei_message.Grid2d._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if Line2d in parents: return 0
        newparents = parents + [Line2d]
        tmphash = (0x96dcacf370554cc3+ baofei_message.Grid2d._get_hash_recursive(newparents)+ baofei_message.Grid2d._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Line2d._packed_fingerprint is None:
            Line2d._packed_fingerprint = struct.pack(">Q", Line2d._get_hash_recursive([]))
        return Line2d._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Line2d._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.start.from_dict(j["start"])
        self.end.from_dict(j["end"])

    def to_dict(self):
        j = {}
        j["start"] = self.start.to_dict()
        j["end"] = self.end.to_dict()
        return j

