"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

class MapName(object):
    __slots__ = ["mapSign", "name"]

    __typenames__ = ["int32_t", "string"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.mapSign = 0
        self.name = ""

    def encode(self):
        buf = BytesIO()
        buf.write(MapName._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.mapSign))
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != MapName._get_packed_fingerprint():
            raise ValueError("Decode error")
        return MapName._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = MapName()
        self.mapSign = struct.unpack(">i", buf.read(4))[0]
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if MapName in parents: return 0
        tmphash = (0x8b2c328bc5a9ca8d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if MapName._packed_fingerprint is None:
            MapName._packed_fingerprint = struct.pack(">Q", MapName._get_hash_recursive([]))
        return MapName._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", MapName._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.mapSign = j["mapSign"]
        self.name = j["name"]

    def to_dict(self):
        j = {}
        j["mapSign"] = self.mapSign
        j["name"] = self.name
        return j

