"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

import baofei_message.Grid2d

class Rect2d(object):
    __slots__ = ["lt", "rb"]

    __typenames__ = ["baofei_message.Grid2d", "baofei_message.Grid2d"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.lt = baofei_message.Grid2d()
        self.rb = baofei_message.Grid2d()

    def encode(self):
        buf = BytesIO()
        buf.write(Rect2d._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.lt._get_packed_fingerprint() == baofei_message.Grid2d._get_packed_fingerprint()
        self.lt._encode_one(buf)
        assert self.rb._get_packed_fingerprint() == baofei_message.Grid2d._get_packed_fingerprint()
        self.rb._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Rect2d._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Rect2d._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Rect2d()
        self.lt = baofei_message.Grid2d._decode_one(buf)
        self.rb = baofei_message.Grid2d._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if Rect2d in parents: return 0
        newparents = parents + [Rect2d]
        tmphash = (0x26c740026db0ef0+ baofei_message.Grid2d._get_hash_recursive(newparents)+ baofei_message.Grid2d._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Rect2d._packed_fingerprint is None:
            Rect2d._packed_fingerprint = struct.pack(">Q", Rect2d._get_hash_recursive([]))
        return Rect2d._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Rect2d._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.lt.from_dict(j["lt"])
        self.rb.from_dict(j["rb"])

    def to_dict(self):
        j = {}
        j["lt"] = self.lt.to_dict()
        j["rb"] = self.rb.to_dict()
        return j

