"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

import baofei_message.Region

class Regions(object):
    __slots__ = ["count", "regions"]

    __typenames__ = ["int8_t", "baofei_message.Region"]

    __dimensions__ = [None, ["count"]]

    def __init__(self):
        self.count = 0
        self.regions = []

    def encode(self):
        buf = BytesIO()
        buf.write(Regions._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.count))
        for i0 in range(self.count):
            assert self.regions[i0]._get_packed_fingerprint() == baofei_message.Region._get_packed_fingerprint()
            self.regions[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Regions._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Regions._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Regions()
        self.count = struct.unpack(">b", buf.read(1))[0]
        self.regions = []
        for i0 in range(self.count):
            self.regions.append(baofei_message.Region._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if Regions in parents: return 0
        newparents = parents + [Regions]
        tmphash = (0x417e54e0c26ce4a8+ baofei_message.Region._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Regions._packed_fingerprint is None:
            Regions._packed_fingerprint = struct.pack(">Q", Regions._get_hash_recursive([]))
        return Regions._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Regions._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.count = j["count"]
        self.regions = [x.from_dict() for x in j["regions"]]

    def to_dict(self):
        j = {}
        j["count"] = self.count
        j["regions"] = [x.to_dict() for x in self.regions]
        return j

