"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

class RegionClean(object):
    __slots__ = ["regionNo", "cleanNum", "mode", "fan", "waterTank", "mopMode", "washWorkType", "wipeMode"]

    __typenames__ = ["int8_t", "int8_t", "int8_t", "int8_t", "int8_t", "int8_t", "int8_t", "int8_t"]

    __dimensions__ = [None, None, None, None, None, None, None, None]

    def __init__(self):
        self.regionNo = 0
        self.cleanNum = 0
        self.mode = 0
        self.fan = 0
        self.waterTank = 0
        self.mopMode = 0
        self.washWorkType = 0
        self.wipeMode = 0

    def encode(self):
        buf = BytesIO()
        buf.write(RegionClean._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bbbbbbbb", self.regionNo, self.cleanNum, self.mode, self.fan, self.waterTank, self.mopMode, self.washWorkType, self.wipeMode))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != RegionClean._get_packed_fingerprint():
            raise ValueError("Decode error")
        return RegionClean._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = RegionClean()
        self.regionNo, self.cleanNum, self.mode, self.fan, self.waterTank, self.mopMode, self.washWorkType, self.wipeMode = struct.unpack(">bbbbbbbb", buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if RegionClean in parents: return 0
        tmphash = (0xe9a94908f47ce6ed) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if RegionClean._packed_fingerprint is None:
            RegionClean._packed_fingerprint = struct.pack(">Q", RegionClean._get_hash_recursive([]))
        return RegionClean._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", RegionClean._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.regionNo = j["regionNo"]
        self.cleanNum = j["cleanNum"]
        self.mode = j["mode"]
        self.fan = j["fan"]
        self.waterTank = j["waterTank"]
        self.mopMode = j["mopMode"]
        self.washWorkType = j["washWorkType"]
        self.wipeMode = j["wipeMode"]

    def to_dict(self):
        j = {}
        j["regionNo"] = self.regionNo
        j["cleanNum"] = self.cleanNum
        j["mode"] = self.mode
        j["fan"] = self.fan
        j["waterTank"] = self.waterTank
        j["mopMode"] = self.mopMode
        j["washWorkType"] = self.washWorkType
        j["wipeMode"] = self.wipeMode
        return j

