"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class AppSetRoomName(object):
    __slots__ = ["version", "count", "roomId", "name"]

    __typenames__ = ["int8_t", "int8_t", "int8_t", "string"]

    __dimensions__ = [None, None, ["count"], ["count"]]

    def __init__(self):
        self.version = 0
        self.count = 0
        self.roomId = []
        self.name = []

    def encode(self):
        buf = BytesIO()
        buf.write(AppSetRoomName._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bb", self.version, self.count))
        buf.write(struct.pack('>%db' % self.count, *self.roomId[:self.count]))
        for i0 in range(self.count):
            __name_encoded = self.name[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__name_encoded)+1))
            buf.write(__name_encoded)
            buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != AppSetRoomName._get_packed_fingerprint():
            raise ValueError("Decode error")
        return AppSetRoomName._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = AppSetRoomName()
        self.version, self.count = struct.unpack(">bb", buf.read(2))
        self.roomId = struct.unpack('>%db' % self.count, buf.read(self.count))
        self.name = []
        for i0 in range(self.count):
            __name_len = struct.unpack('>I', buf.read(4))[0]
            self.name.append(buf.read(__name_len)[:-1].decode('utf-8', 'replace'))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if AppSetRoomName in parents: return 0
        tmphash = (0xf13110646feb3843) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if AppSetRoomName._packed_fingerprint is None:
            AppSetRoomName._packed_fingerprint = struct.pack(">Q", AppSetRoomName._get_hash_recursive([]))
        return AppSetRoomName._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", AppSetRoomName._get_packed_fingerprint())[0]

