"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class RobotStatus(object):
    __slots__ = ["battLevel", "battStatus", "error", "carpet"]

    __typenames__ = ["int8_t", "int8_t", "int32_t", "int8_t"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.battLevel = 0
        self.battStatus = 0
        self.error = 0
        self.carpet = 0

    def encode(self):
        buf = BytesIO()
        buf.write(RobotStatus._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bbib", self.battLevel, self.battStatus, self.error, self.carpet))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != RobotStatus._get_packed_fingerprint():
            raise ValueError("Decode error")
        return RobotStatus._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = RobotStatus()
        self.battLevel, self.battStatus, self.error, self.carpet = struct.unpack(">bbib", buf.read(7))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if RobotStatus in parents: return 0
        tmphash = (0x7d0ea30ed63b92e2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if RobotStatus._packed_fingerprint is None:
            RobotStatus._packed_fingerprint = struct.pack(">Q", RobotStatus._get_hash_recursive([]))
        return RobotStatus._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", RobotStatus._get_packed_fingerprint())[0]

