"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class Shell(object):
    __slots__ = ["count", "code"]

    __typenames__ = ["int8_t", "int8_t"]

    __dimensions__ = [None, ["count"]]

    def __init__(self):
        self.count = 0
        self.code = []

    def encode(self):
        buf = BytesIO()
        buf.write(Shell._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.count))
        buf.write(struct.pack('>%db' % self.count, *self.code[:self.count]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Shell._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Shell._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Shell()
        self.count = struct.unpack(">b", buf.read(1))[0]
        self.code = struct.unpack('>%db' % self.count, buf.read(self.count))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if Shell in parents: return 0
        tmphash = (0xd9ca675dcb56a3c7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Shell._packed_fingerprint is None:
            Shell._packed_fingerprint = struct.pack(">Q", Shell._get_hash_recursive([]))
        return Shell._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Shell._get_packed_fingerprint())[0]

