/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __baofei_message_RobotArea_hpp__
#define __baofei_message_RobotArea_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>
#include "baofei_message/RectArea.hpp"
#include "baofei_message/RectArea.hpp"

namespace baofei_message
{

class RobotArea
{
    public:
        int8_t     cleanCount;

        std::vector< baofei_message::RectArea > clean;

        int8_t     forbiddenCount;

        std::vector< baofei_message::RectArea > forbidden;

#ifdef __NLOHMANN_JSON_CPP
    public:
        NLOHMANN_DEFINE_TYPE_INTRUSIVE(RobotArea, cleanCount, clean, forbiddenCount, forbidden)
#endif
#ifdef __MSGPACK
    public:
        MSGPACK_DEFINE(RobotArea, cleanCount, clean, forbiddenCount, forbidden)
#endif
    public:
        bool operator==(const RobotArea& other) const
        {
            return cleanCount == other.cleanCount && clean == other.clean && forbiddenCount == other.forbiddenCount && forbidden == other.forbidden;
        }
    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "RobotArea"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int RobotArea::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int RobotArea::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int RobotArea::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t RobotArea::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* RobotArea::getTypeName()
{
    return "RobotArea";
}

int RobotArea::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->cleanCount, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->cleanCount; a0++) {
        tlen = this->clean[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->forbiddenCount, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->forbiddenCount; a0++) {
        tlen = this->forbidden[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int RobotArea::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->cleanCount, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->clean.resize(this->cleanCount);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->cleanCount; a0++) {
        tlen = this->clean[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->forbiddenCount, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->forbidden.resize(this->forbiddenCount);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->forbiddenCount; a0++) {
        tlen = this->forbidden[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int RobotArea::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->cleanCount; a0++) {
        enc_size += this->clean[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->forbiddenCount; a0++) {
        enc_size += this->forbidden[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

uint64_t RobotArea::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == RobotArea::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, RobotArea::getHash };

    uint64_t hash = 0x7254da9ceb8e013dLL +
         baofei_message::RectArea::_computeHash(&cp) +
         baofei_message::RectArea::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
