"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

class AlarmInfo(object):
    __slots__ = ["appName", "logType", "logValue"]

    __typenames__ = ["string", "string", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.appName = ""
        self.logType = ""
        self.logValue = ""

    def encode(self):
        buf = BytesIO()
        buf.write(AlarmInfo._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __appName_encoded = self.appName.encode('utf-8')
        buf.write(struct.pack('>I', len(__appName_encoded)+1))
        buf.write(__appName_encoded)
        buf.write(b"\0")
        __logType_encoded = self.logType.encode('utf-8')
        buf.write(struct.pack('>I', len(__logType_encoded)+1))
        buf.write(__logType_encoded)
        buf.write(b"\0")
        __logValue_encoded = self.logValue.encode('utf-8')
        buf.write(struct.pack('>I', len(__logValue_encoded)+1))
        buf.write(__logValue_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != AlarmInfo._get_packed_fingerprint():
            raise ValueError("Decode error")
        return AlarmInfo._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = AlarmInfo()
        __appName_len = struct.unpack('>I', buf.read(4))[0]
        self.appName = buf.read(__appName_len)[:-1].decode('utf-8', 'replace')
        __logType_len = struct.unpack('>I', buf.read(4))[0]
        self.logType = buf.read(__logType_len)[:-1].decode('utf-8', 'replace')
        __logValue_len = struct.unpack('>I', buf.read(4))[0]
        self.logValue = buf.read(__logValue_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if AlarmInfo in parents: return 0
        tmphash = (0x6fae75a6b31e8806) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if AlarmInfo._packed_fingerprint is None:
            AlarmInfo._packed_fingerprint = struct.pack(">Q", AlarmInfo._get_hash_recursive([]))
        return AlarmInfo._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", AlarmInfo._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.appName = j["appName"]
        self.logType = j["logType"]
        self.logValue = j["logValue"]

    def to_dict(self):
        j = {}
        j["appName"] = self.appName
        j["logType"] = self.logType
        j["logValue"] = self.logValue
        return j

