"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

import mars_message.Polygon

class AppCarpet(object):
    __slots__ = ["version", "count", "type", "carpet"]

    __typenames__ = ["int8_t", "int8_t", "int8_t", "mars_message.Polygon"]

    __dimensions__ = [None, None, ["count"], ["count"]]

    def __init__(self):
        self.version = 0
        self.count = 0
        self.type = []
        self.carpet = []

    def encode(self):
        buf = BytesIO()
        buf.write(AppCarpet._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bb", self.version, self.count))
        buf.write(struct.pack('>%db' % self.count, *self.type[:self.count]))
        for i0 in range(self.count):
            assert self.carpet[i0]._get_packed_fingerprint() == mars_message.Polygon._get_packed_fingerprint()
            self.carpet[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != AppCarpet._get_packed_fingerprint():
            raise ValueError("Decode error")
        return AppCarpet._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = AppCarpet()
        self.version, self.count = struct.unpack(">bb", buf.read(2))
        self.type = struct.unpack('>%db' % self.count, buf.read(self.count))
        self.carpet = []
        for i0 in range(self.count):
            self.carpet.append(mars_message.Polygon._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if AppCarpet in parents: return 0
        newparents = parents + [AppCarpet]
        tmphash = (0x6ad8a273942b6864+ mars_message.Polygon._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if AppCarpet._packed_fingerprint is None:
            AppCarpet._packed_fingerprint = struct.pack(">Q", AppCarpet._get_hash_recursive([]))
        return AppCarpet._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", AppCarpet._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.version = j["version"]
        self.count = j["count"]
        self.type = j["type"]
        self.carpet = [x.from_dict() for x in j["carpet"]]

    def to_dict(self):
        j = {}
        j["version"] = self.version
        j["count"] = self.count
        j["type"] = self.type
        j["carpet"] = [x.to_dict() for x in self.carpet]
        return j

