"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

class AppPartsLife(object):
    __slots__ = ["edgeBrushLifeMinutes", "mainBrushLifeMinutes", "haipaLifeMinutes", "ragLifeMinutes"]

    __typenames__ = ["int16_t", "int16_t", "int16_t", "int16_t"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.edgeBrushLifeMinutes = 0
        self.mainBrushLifeMinutes = 0
        self.haipaLifeMinutes = 0
        self.ragLifeMinutes = 0

    def encode(self):
        buf = BytesIO()
        buf.write(AppPartsLife._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hhhh", self.edgeBrushLifeMinutes, self.mainBrushLifeMinutes, self.haipaLifeMinutes, self.ragLifeMinutes))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != AppPartsLife._get_packed_fingerprint():
            raise ValueError("Decode error")
        return AppPartsLife._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = AppPartsLife()
        self.edgeBrushLifeMinutes, self.mainBrushLifeMinutes, self.haipaLifeMinutes, self.ragLifeMinutes = struct.unpack(">hhhh", buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if AppPartsLife in parents: return 0
        tmphash = (0xcc973b555cf58538) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if AppPartsLife._packed_fingerprint is None:
            AppPartsLife._packed_fingerprint = struct.pack(">Q", AppPartsLife._get_hash_recursive([]))
        return AppPartsLife._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", AppPartsLife._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.edgeBrushLifeMinutes = j["edgeBrushLifeMinutes"]
        self.mainBrushLifeMinutes = j["mainBrushLifeMinutes"]
        self.haipaLifeMinutes = j["haipaLifeMinutes"]
        self.ragLifeMinutes = j["ragLifeMinutes"]

    def to_dict(self):
        j = {}
        j["edgeBrushLifeMinutes"] = self.edgeBrushLifeMinutes
        j["mainBrushLifeMinutes"] = self.mainBrushLifeMinutes
        j["haipaLifeMinutes"] = self.haipaLifeMinutes
        j["ragLifeMinutes"] = self.ragLifeMinutes
        return j

