"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

class Int32(object):
    __slots__ = ["value"]

    __typenames__ = ["int32_t"]

    __dimensions__ = [None]

    def __init__(self):
        self.value = 0

    def encode(self):
        buf = BytesIO()
        buf.write(Int32._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.value))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Int32._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Int32._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Int32()
        self.value = struct.unpack(">i", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if Int32 in parents: return 0
        tmphash = (0xa6869f09f492d897) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Int32._packed_fingerprint is None:
            Int32._packed_fingerprint = struct.pack(">Q", Int32._get_hash_recursive([]))
        return Int32._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Int32._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.value = j["value"]

    def to_dict(self):
        j = {}
        j["value"] = self.value
        return j

