"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

class Ranges(object):
    __slots__ = ["count", "rangeMM"]

    __typenames__ = ["int8_t", "int16_t"]

    __dimensions__ = [None, ["count"]]

    def __init__(self):
        self.count = 0
        self.rangeMM = []

    def encode(self):
        buf = BytesIO()
        buf.write(Ranges._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.count))
        buf.write(struct.pack('>%dh' % self.count, *self.rangeMM[:self.count]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Ranges._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Ranges._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Ranges()
        self.count = struct.unpack(">b", buf.read(1))[0]
        self.rangeMM = struct.unpack('>%dh' % self.count, buf.read(self.count * 2))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if Ranges in parents: return 0
        tmphash = (0x70d190df79f5e85d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Ranges._packed_fingerprint is None:
            Ranges._packed_fingerprint = struct.pack(">Q", Ranges._get_hash_recursive([]))
        return Ranges._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Ranges._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.count = j["count"]
        self.rangeMM = j["rangeMM"]

    def to_dict(self):
        j = {}
        j["count"] = self.count
        j["rangeMM"] = self.rangeMM
        return j

