"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

import mars_message.Point

class AppSpotClean(object):
    __slots__ = ["version", "spot", "mode", "suction", "cistern", "cleanRepeat"]

    __typenames__ = ["int8_t", "mars_message.Point", "int8_t", "int8_t", "int8_t", "int8_t"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.version = 0
        self.spot = mars_message.Point()
        self.mode = 0
        self.suction = 0
        self.cistern = 0
        self.cleanRepeat = 0

    def encode(self):
        buf = BytesIO()
        buf.write(AppSpotClean._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.version))
        assert self.spot._get_packed_fingerprint() == mars_message.Point._get_packed_fingerprint()
        self.spot._encode_one(buf)
        buf.write(struct.pack(">bbbb", self.mode, self.suction, self.cistern, self.cleanRepeat))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != AppSpotClean._get_packed_fingerprint():
            raise ValueError("Decode error")
        return AppSpotClean._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = AppSpotClean()
        self.version = struct.unpack(">b", buf.read(1))[0]
        self.spot = mars_message.Point._decode_one(buf)
        self.mode, self.suction, self.cistern, self.cleanRepeat = struct.unpack(">bbbb", buf.read(4))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if AppSpotClean in parents: return 0
        newparents = parents + [AppSpotClean]
        tmphash = (0xc6cf6143b632a214+ mars_message.Point._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if AppSpotClean._packed_fingerprint is None:
            AppSpotClean._packed_fingerprint = struct.pack(">Q", AppSpotClean._get_hash_recursive([]))
        return AppSpotClean._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", AppSpotClean._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.version = j["version"]
        self.spot.from_dict(j["spot"])
        self.mode = j["mode"]
        self.suction = j["suction"]
        self.cistern = j["cistern"]
        self.cleanRepeat = j["cleanRepeat"]

    def to_dict(self):
        j = {}
        j["version"] = self.version
        j["spot"] = self.spot.to_dict()
        j["mode"] = self.mode
        j["suction"] = self.suction
        j["cistern"] = self.cistern
        j["cleanRepeat"] = self.cleanRepeat
        return j

