"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

class BlueToothState(object):
    __slots__ = ["connect_state"]

    __typenames__ = ["boolean"]

    __dimensions__ = [None]

    def __init__(self):
        self.connect_state = False

    def encode(self):
        buf = BytesIO()
        buf.write(BlueToothState._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.connect_state))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != BlueToothState._get_packed_fingerprint():
            raise ValueError("Decode error")
        return BlueToothState._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = BlueToothState()
        self.connect_state = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if BlueToothState in parents: return 0
        tmphash = (0xd49c1bed1dd222ce) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if BlueToothState._packed_fingerprint is None:
            BlueToothState._packed_fingerprint = struct.pack(">Q", BlueToothState._get_hash_recursive([]))
        return BlueToothState._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", BlueToothState._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.connect_state = j["connect_state"]

    def to_dict(self):
        j = {}
        j["connect_state"] = self.connect_state
        return j

