"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

class FactoryTestConfig(object):
    __slots__ = ["gtSpeedMinLimit", "batteryVolMaxLimit", "batteryVolMinLimit", "batteryCurrentMaxLimit", "batteryCurrentMinLimit", "waterBumpMinLimit", "airBumpMinLimit"]

    __typenames__ = ["int32_t", "int32_t", "int32_t", "int32_t", "int32_t", "int32_t", "int32_t"]

    __dimensions__ = [None, None, None, None, None, None, None]

    def __init__(self):
        self.gtSpeedMinLimit = 0
        self.batteryVolMaxLimit = 0
        self.batteryVolMinLimit = 0
        self.batteryCurrentMaxLimit = 0
        self.batteryCurrentMinLimit = 0
        self.waterBumpMinLimit = 0
        self.airBumpMinLimit = 0

    def encode(self):
        buf = BytesIO()
        buf.write(FactoryTestConfig._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iiiiiii", self.gtSpeedMinLimit, self.batteryVolMaxLimit, self.batteryVolMinLimit, self.batteryCurrentMaxLimit, self.batteryCurrentMinLimit, self.waterBumpMinLimit, self.airBumpMinLimit))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != FactoryTestConfig._get_packed_fingerprint():
            raise ValueError("Decode error")
        return FactoryTestConfig._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = FactoryTestConfig()
        self.gtSpeedMinLimit, self.batteryVolMaxLimit, self.batteryVolMinLimit, self.batteryCurrentMaxLimit, self.batteryCurrentMinLimit, self.waterBumpMinLimit, self.airBumpMinLimit = struct.unpack(">iiiiiii", buf.read(28))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if FactoryTestConfig in parents: return 0
        tmphash = (0x3639dfb4e6ed262d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if FactoryTestConfig._packed_fingerprint is None:
            FactoryTestConfig._packed_fingerprint = struct.pack(">Q", FactoryTestConfig._get_hash_recursive([]))
        return FactoryTestConfig._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", FactoryTestConfig._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.gtSpeedMinLimit = j["gtSpeedMinLimit"]
        self.batteryVolMaxLimit = j["batteryVolMaxLimit"]
        self.batteryVolMinLimit = j["batteryVolMinLimit"]
        self.batteryCurrentMaxLimit = j["batteryCurrentMaxLimit"]
        self.batteryCurrentMinLimit = j["batteryCurrentMinLimit"]
        self.waterBumpMinLimit = j["waterBumpMinLimit"]
        self.airBumpMinLimit = j["airBumpMinLimit"]

    def to_dict(self):
        j = {}
        j["gtSpeedMinLimit"] = self.gtSpeedMinLimit
        j["batteryVolMaxLimit"] = self.batteryVolMaxLimit
        j["batteryVolMinLimit"] = self.batteryVolMinLimit
        j["batteryCurrentMaxLimit"] = self.batteryCurrentMaxLimit
        j["batteryCurrentMinLimit"] = self.batteryCurrentMinLimit
        j["waterBumpMinLimit"] = self.waterBumpMinLimit
        j["airBumpMinLimit"] = self.airBumpMinLimit
        return j

