"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

class IrCode2(object):
    __slots__ = ["timestampMs", "code0", "code1", "code2", "code3"]

    __typenames__ = ["int32_t", "int32_t", "int32_t", "int32_t", "int32_t"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.timestampMs = 0
        self.code0 = 0
        self.code1 = 0
        self.code2 = 0
        self.code3 = 0

    def encode(self):
        buf = BytesIO()
        buf.write(IrCode2._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iiiii", self.timestampMs, self.code0, self.code1, self.code2, self.code3))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != IrCode2._get_packed_fingerprint():
            raise ValueError("Decode error")
        return IrCode2._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = IrCode2()
        self.timestampMs, self.code0, self.code1, self.code2, self.code3 = struct.unpack(">iiiii", buf.read(20))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if IrCode2 in parents: return 0
        tmphash = (0x46c7898c51076384) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if IrCode2._packed_fingerprint is None:
            IrCode2._packed_fingerprint = struct.pack(">Q", IrCode2._get_hash_recursive([]))
        return IrCode2._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", IrCode2._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.timestampMs = j["timestampMs"]
        self.code0 = j["code0"]
        self.code1 = j["code1"]
        self.code2 = j["code2"]
        self.code3 = j["code3"]

    def to_dict(self):
        j = {}
        j["timestampMs"] = self.timestampMs
        j["code0"] = self.code0
        j["code1"] = self.code1
        j["code2"] = self.code2
        j["code3"] = self.code3
        return j

