"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

class LaserScan(object):
    __slots__ = ["timestampMs", "angleMin", "angleMax", "angleIncrement", "timeIncrement", "scanTime", "rangeMin", "rangeMax", "count", "ranges", "intensities"]

    __typenames__ = ["int64_t", "float", "float", "float", "float", "float", "float", "float", "int32_t", "float", "float"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, ["count"], ["count"]]

    def __init__(self):
        self.timestampMs = 0
        self.angleMin = 0.0
        self.angleMax = 0.0
        self.angleIncrement = 0.0
        self.timeIncrement = 0.0
        self.scanTime = 0.0
        self.rangeMin = 0.0
        self.rangeMax = 0.0
        self.count = 0
        self.ranges = []
        self.intensities = []

    def encode(self):
        buf = BytesIO()
        buf.write(LaserScan._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qfffffffi", self.timestampMs, self.angleMin, self.angleMax, self.angleIncrement, self.timeIncrement, self.scanTime, self.rangeMin, self.rangeMax, self.count))
        buf.write(struct.pack('>%df' % self.count, *self.ranges[:self.count]))
        buf.write(struct.pack('>%df' % self.count, *self.intensities[:self.count]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != LaserScan._get_packed_fingerprint():
            raise ValueError("Decode error")
        return LaserScan._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = LaserScan()
        self.timestampMs, self.angleMin, self.angleMax, self.angleIncrement, self.timeIncrement, self.scanTime, self.rangeMin, self.rangeMax, self.count = struct.unpack(">qfffffffi", buf.read(40))
        self.ranges = struct.unpack('>%df' % self.count, buf.read(self.count * 4))
        self.intensities = struct.unpack('>%df' % self.count, buf.read(self.count * 4))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if LaserScan in parents: return 0
        tmphash = (0x5b820cc0794077cf) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if LaserScan._packed_fingerprint is None:
            LaserScan._packed_fingerprint = struct.pack(">Q", LaserScan._get_hash_recursive([]))
        return LaserScan._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", LaserScan._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.timestampMs = j["timestampMs"]
        self.angleMin = j["angleMin"]
        self.angleMax = j["angleMax"]
        self.angleIncrement = j["angleIncrement"]
        self.timeIncrement = j["timeIncrement"]
        self.scanTime = j["scanTime"]
        self.rangeMin = j["rangeMin"]
        self.rangeMax = j["rangeMax"]
        self.count = j["count"]
        self.ranges = j["ranges"]
        self.intensities = j["intensities"]

    def to_dict(self):
        j = {}
        j["timestampMs"] = self.timestampMs
        j["angleMin"] = self.angleMin
        j["angleMax"] = self.angleMax
        j["angleIncrement"] = self.angleIncrement
        j["timeIncrement"] = self.timeIncrement
        j["scanTime"] = self.scanTime
        j["rangeMin"] = self.rangeMin
        j["rangeMax"] = self.rangeMax
        j["count"] = self.count
        j["ranges"] = self.ranges
        j["intensities"] = self.intensities
        return j

