"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

import mars_message.DateTime

import mars_message.Order

class Orders(object):
    __slots__ = ["robotTime", "timezone", "num", "orders"]

    __typenames__ = ["mars_message.DateTime", "int8_t", "int32_t", "mars_message.Order"]

    __dimensions__ = [None, None, None, ["num"]]

    def __init__(self):
        self.robotTime = mars_message.DateTime()
        self.timezone = 0
        self.num = 0
        self.orders = []

    def encode(self):
        buf = BytesIO()
        buf.write(Orders._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.robotTime._get_packed_fingerprint() == mars_message.DateTime._get_packed_fingerprint()
        self.robotTime._encode_one(buf)
        buf.write(struct.pack(">bi", self.timezone, self.num))
        for i0 in range(self.num):
            assert self.orders[i0]._get_packed_fingerprint() == mars_message.Order._get_packed_fingerprint()
            self.orders[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Orders._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Orders._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Orders()
        self.robotTime = mars_message.DateTime._decode_one(buf)
        self.timezone, self.num = struct.unpack(">bi", buf.read(5))
        self.orders = []
        for i0 in range(self.num):
            self.orders.append(mars_message.Order._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if Orders in parents: return 0
        newparents = parents + [Orders]
        tmphash = (0xc958c5ff8332221b+ mars_message.DateTime._get_hash_recursive(newparents)+ mars_message.Order._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Orders._packed_fingerprint is None:
            Orders._packed_fingerprint = struct.pack(">Q", Orders._get_hash_recursive([]))
        return Orders._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Orders._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.robotTime.from_dict(j["robotTime"])
        self.timezone = j["timezone"]
        self.num = j["num"]
        self.orders = [x.from_dict() for x in j["orders"]]

    def to_dict(self):
        j = {}
        j["robotTime"] = self.robotTime.to_dict()
        j["timezone"] = self.timezone
        j["num"] = self.num
        j["orders"] = [x.to_dict() for x in self.orders]
        return j

