"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

class Range(object):
    __slots__ = ["rangeMM"]

    __typenames__ = ["int16_t"]

    __dimensions__ = [None]

    def __init__(self):
        self.rangeMM = 0

    def encode(self):
        buf = BytesIO()
        buf.write(Range._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">h", self.rangeMM))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Range._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Range._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Range()
        self.rangeMM = struct.unpack(">h", buf.read(2))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if Range in parents: return 0
        tmphash = (0x4e3151b76595f92c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Range._packed_fingerprint is None:
            Range._packed_fingerprint = struct.pack(">Q", Range._get_hash_recursive([]))
        return Range._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Range._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.rangeMM = j["rangeMM"]

    def to_dict(self):
        j = {}
        j["rangeMM"] = self.rangeMM
        return j

